

export const types = {
    // Sync
    FILL_POST: 'FILL_POST',
    CREATE_POST: 'CREATE_POST',
    //  REMOVE_POST: 'REMOVE_POST',
  
    
    //Async
    FETCH_POSTS_ASYNC : 'FETCH_POSTS_ASYNC',
    CREATE_POST_ASYNC: 'CREATE_POST_ASYNC',
    //  REMOVE_POST_ASYNC: 'REMOVE_POST_ASYNC',

};